### ISSUE TITLE
Parameter in parallel_map.sh should be updated

### ISSUE THREAD

**Issue by 0m1n0** [itai-levin/hybmind#1]
https://github.com/itai-levin/hybmind/blob/8cca65e3cd4d52add1108645014fd34a65bcb096/process_BKMS_database/scripts/parallel_map.sh#L14C1-L14C44

Hi @itai-levin 

I'm reproducing the part of Process BKMS database.
In the code of `parallel_map.sh`, you should change `-f4` to `-f1` to be consistent with the data available on your repository.

Thanks!
Min

**Comment by itai-levin** [comment]
Thank you for pointing this out! 
I've changed the way that the line counting is performed in commit `9f097b2`. Should resolve the issue.
